### ISSUE TITLE
How To Reach You & What Happened to MonsieurET

### ISSUE THREAD

**Issue by jlpoolen** [MonsieurETH/MonsieurETH#1]
I found a link at:  

  https://discussions.flightaware.com/t/tool-for-decoding-beast-format-ads-b-data/17007/9

which points to 

   https://github.com/MonsieurET/ADSMySQL

and the above link no longer resolves; the account of MonsieurET looks to be closed.  I found this account, MonsieurETH, which I am presuming is a continuation of the MonsieurET account.  The README to this account has an invitation to reach you through Gmail and Twitter, yet the underlying links do nothing but show an image icon.  So I am resorting to filing this Issue to reach you.

So:

1) is MonsieurETH a continuation of the account MonsieurET
2) where can I see the benefit of your analysis of ads-b parsing for database storage?

**Comment by MonsieurETH** [comment]
Hi @jlpoolen, there is no relation between this account and the one you're referring, so I can't assist you. Sorry and good luck with your search.
